
spring:
  shell:
    interactive:
      enabled: true
  application:
    name: sbdocs
  datasource:
    url: jdbc:postgresql://localhost:5432/sbdocs
    username: admin
    password: password
  docker:
    compose:
      lifecycle-management: START_ONLY
  ai:
#    google:
#      genai:
#        api-key: ${GEMINI_API_KEY}
#        chat:
#          options:
#            model: gemini-2.5-flash
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:0.5b
          num-ctx: 2048

      embedding:
        model: nomic-embed-fast-custom
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
logging:
  level:
    root: info
#    google:
#      genai:
#        api-key: ${GEMINI_API_KEY}
#        chat:
#          options:
##            model: gemini-2-flash
#            model: gemini-embedding-001
#
#        embedding:
#          api-key: ${GEMINI_API_KEY}
#          text:
#            options:
#              model: gemini-embedding-001
  #spring.ai.google.genai.chat.options.temperature=0.7
  # Explicitly enable embeddings (optional, usually true by default)
  #spring.ai.model.embedding.text=google-genai
#spring.ai.google.genai.project-id=SpringAI