

spring:
  application:
    name: sbdocs
  datasource:
    url: jdbc:postgresql://localhost:5432/sbdocs
    username: admin
    password: password
  docker:
    compose:
      lifecycle-management: START_ONLY
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            options:
              model: gemini-embedding-001
  #spring.ai.google.genai.chat.options.temperature=0.7
  # Explicitly enable embeddings (optional, usually true by default)
  #spring.ai.model.embedding.text=google-genai
#spring.ai.google.genai.project-id=SpringAI