spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: USER-SERVICE
              uri: lb://UserService
              predicates:
                - Path=/users/**

            - id: HOTEL-SERVICE
              uri: lb://HotelService
              predicates:
                - Path=/hotels/**,/staffs/**

            - id: RATING-SERVICE
              uri: lb://RatingService
              predicates:
                - Path=/ratings/**

  config:
    import: optional:configserver:http://localhost:8085
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID}
            client-secret: ${OKTA_CLIENT_SECRET}
#            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://dev-xmv044k57mtbkxo1.us.auth0.com/oauth2/default


server:
  port: 8084


# OAUTH0(okta) configs for API Gateway
#okta:
#  oauth2:
#    issuer: https://dev-xmv044k57mtbkxo1.us.auth0.com
#    client-id: rL0DdMbgNAvAtQ6F6e28Vg5FoceLjcZ3
#    client-secret: kFDWfIcNdnaTC4HJI-p06VdMKoO5zdKVtXD4t4zNftnQA7yUoIpHpigewv98Sv-n
#    scopes: openid, profile, email, offline_access



#No need of below configurations as they are now fetched from GitHub using ConfigServer

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka