spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: USER-SERVICE
              uri: lb://UserService
              predicates:
                - Path=/users/**

            - id: HOTEL-SERVICE
              uri: lb://HotelService
              predicates:
                - Path=/hotels/**,/staffs/**

            - id: RATING-SERVICE
              uri: lb://RatingService
              predicates:
                - Path=/ratings/**

  config:
    import: optional:configserver:http://localhost:8085

server:
  port: 8084



#No need of below configurations as they are now fetched from GitHub using ConfigServer

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka